### ISSUE TITLE
No tables appear

### ISSUE THREAD

**Issue by davidagiraldo** [ijgnd/anki__editor_jseditor_for_current_field#1]
Hello,

I first added this add-on "extended (table) editor".

I then copied the table from my text editor (Microsoft word), pasted the table in Anki and what I expected was to see a table. But non exists. Am I doing something incorrect? See below the screen shots.
 
![Screen Shot 2019-09-21 at 8 12 57 PM](https://user-images.githubusercontent.com/20512697/65380583-46186400-dcac-11e9-8ea6-21a826428e10.png)

![Screen Shot 2019-09-21 at 8 13 48 PM](https://user-images.githubusercontent.com/20512697/65380591-61836f00-dcac-11e9-9cf4-9565db04fd3c.png)

Sincerely,
Oceanswim

**Comment by ijgnd** [comment]
Sorry for answering so late. I somehow missed your comment. 

If it's still relevant: When you paste the normal way (Ctrl+V) into the Anki editor Anki removes a lot of formatting. To keep a little bit more formatting try try "Ctrl+SHIFT+V" this should keep the table (but set the border colors to invisible ...)

My add-on is not active all the time. You must manually start it for the current field (the field where your cursor is) by pressing the button "T4". It's the right most button in your button bar in your second screenshot. But this external editor also removes some html formatting - mainly because MS Word adds so much styling that it always looks somehow broken/off in other editors.

In my add-on window a pasted table might also be processed so much that it's kind of invisible - but when you right click where the table should be I always get formatting options and e.g. can set the cell properties and then select a solid border.
